universe = vanilla

Executable = FlatSignal_generationcampaign/condor_mass_low_1to50_mpiEqMrho_lxplus/run_mass_point_lxplus.sh

Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT

Transfer_Input_Files = FlatSignal_generationcampaign/condor_mass_low_1to50_mpiEqMrho_lxplus/model_building_production.tgz, FlatSignal_generationcampaign/condor_mass_low_1to50_mpiEqMrho_lxplus/mass_points_low_1to50.txt

Output = FlatSignal_generationcampaign/condor_mass_low_1to50_mpiEqMrho_lxplus/logs/low_1to50_$(Cluster)_$(Process).out
Error  = FlatSignal_generationcampaign/condor_mass_low_1to50_mpiEqMrho_lxplus/logs/low_1to50_$(Cluster)_$(Process).err
Log    = FlatSignal_generationcampaign/condor_mass_low_1to50_mpiEqMrho_lxplus/logs/low_1to50_$(Cluster).log

request_cpus   = 1
request_memory = 4 GB
request_disk   = 20 GB

+JobFlavour = "workday"

Arguments = $(Process) mass_points_low_1to50.txt 300 /eos/project/d/dragon/ashrivas/DarkHadronMassReco/DataForDragon_lowMass_1to50 root://eosproject.cern.ch

Queue 19604
